#!/bin/sh
# Build the App Store upload package: the artefact, and nothing that is not the artefact.
#
# This exists because the deploy gate found there was no artefact at all, so the thing
# that would be uploaded had never been built or tested. A plausible hand-assembled
# allowlist then went RED on the platform's own test stage in seconds, because the suite
# reads files from the package ROOT and two of them had not been shipped. A package is
# not a tarball of the repository and it is not the image build context either: the image
# excludes `tests/`, the platform requires them.
#
# Flat, with the Dockerfile at the root. A nested Dockerfile breaks both template
# detection and the build context, which is a recorded failure on this platform.
#
# Pure POSIX sh, like the verification loop, for the same reason.
set -eu

ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

# The content sweep below needs an interpreter. The project's own is preferred; a system
# python3 is accepted so the package can still be built on a machine without the virtual
# environment, and the absence of both is a hard failure rather than a silent skip, because
# this is a credential control.
PY_FOR_SWEEP=""
for candidate in "${PYTHON:-.venv/bin/python}" python3; do
  if command -v "$candidate" >/dev/null 2>&1; then PY_FOR_SWEEP="$candidate"; break; fi
done
[ -n "$PY_FOR_SWEEP" ] || { echo "FAIL: no interpreter for the credential sweep"; exit 1; }

VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -1)"
# A version with a slash in it makes $OUT and `basename "$OUT"` disagree, so the zip is
# written to one path while a different one is recorded, hashed and pointed at.
case "$VERSION" in
  "" | *[!0-9.]* ) echo "FAIL: implausible version '$VERSION' in pyproject.toml"; exit 1 ;;
esac
STAMP="$(date -u +%Y%m%d)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo nogit)"
# A package from a tree with uncommitted changes is stamped as such, so the simulation can
# refuse it. Without this, commit granularity admits a package built before an edit and the
# simulation reports PASS for a tree whose package was never built.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  COMMIT="${COMMIT}-dirty"
fi
OUT="dist/comply-ops-${VERSION}-${STAMP}-${COMMIT}.zip"
STAGE="dist/.stage"
# Under the stage prefix so the same `rm -rf` clears it, and so it is never written
# through a path an attacker can place in `dist/` ahead of the build.
MANIFEST="dist/.stage.manifest"

# Every path that ships. Anything not named here is not in the package, so a new file
# that a test reads must be added HERE as well as written, and the assertion below is
# what catches the omission before the platform does.
FILES="Dockerfile
.dockerignore
.env.example
.python-version
pyproject.toml
sonar-project.properties
requirements-runtime.in
requirements-runtime.txt
requirements.in
requirements.txt
requirements-dev.in
requirements-dev.txt
wsgi.py
README.md
SECURITY.md
CHANGELOG.md"
DIRS="src
tests
docs
scripts"

# What is deliberately NOT shipped, and why, so the next person does not add it back:
#   .git, .github, .claude   history, CI and the assistant baseline are not the product
#   .venv, __pycache__       local build output
#   data/                    runtime state; the volume supplies it
#   dist/                    this script's own output
#   coverage.xml, sbom.*     regenerated by the platform's own run; a stale copy misleads
#   CLAUDE.md, READINESS.md  internal working documents
#   .gitlab-ci.yml           the platform generates its own pipeline; a shipped copy is
#                            inert at best and misleading at worst

# Invalidate the pointer BEFORE building, not after. It was only ever written on success
# and never cleared, so a build that failed left the previous commit's package still
# pointed at, and the simulation would test that stale artefact and report PASS for a tree
# whose package never built. Reproduced in a throwaway clone.
mkdir -p dist
rm -f dist/latest dist/latest.sha256 dist/.latest.tmp dist/.latest.sha.tmp
rm -rf "$STAGE" "$OUT" "$MANIFEST"
mkdir -p "$STAGE"

for path in $FILES; do
  [ -f "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
done
for path in $DIRS; do
  [ -d "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
done

# The stage is materialised from the OBJECT DATABASE, not from a walk of the working tree,
# and that is a security boundary rather than a tidiness preference. Two attacks made the
# case, both demonstrated rather than theorised.
#
# A directory copy ships whatever is on disk. A git-ignored `src/.env` is invisible to
# `git status`, so the tree reads clean, the package is stamped with a clean commit, and the
# secret is inside it. Reading the file list from `git ls-files` closed that, and left a
# second hole open: `cp` dereferences a symlink at any INTERMEDIATE path component, so
# replacing `docs/` with a link to a directory outside the tree put host-side content into
# the artefact while every leaf-level check passed. The sweep could not see it, because `cp`
# had already resolved it.
#
# `git archive HEAD` ends the class rather than narrowing it again. The bytes come from the
# committed tree, so an ignored file, an untracked file, a symlinked directory component, a
# hardlink swapped in on disk and an `assume-unchanged` bit are all equally invisible: none
# of them is in HEAD.
#
# The consequence is worth stating plainly. The package always contains HEAD, never the
# working tree. On a dirty tree it therefore packages the committed content and the `-dirty`
# stamp says so, which is the honest signal: the artefact does not represent what you are
# looking at.
# shellcheck disable=SC2086  # deliberate: both are newline-separated allowlists of
# literal paths this file controls, each checked to exist immediately above.
git archive HEAD -- $FILES $DIRS | tar -x -C "$STAGE"
[ -n "$(find "$STAGE" -type f -print -quit)" ] || { echo "FAIL: git archive produced nothing"; exit 1; }

# `git archive` is NOT a byte-faithful copy of HEAD, and believing it was is what the
# comment above got wrong. It applies the archived tree's own `.gitattributes` and the build
# host's conversion settings, all of which an attacker reaches from a single committed file:
#
#   export-ignore   removes a path from the archive. One committed line deleted the
#                   AMD-001 10.6 security header test from the package, the build exited 0,
#                   and the pipeline simulation returned SIMULATION: PASS on an artefact
#                   with the control's test missing.
#   export-subst    substitutes attacker-chosen commit-message text into a shipped file.
#   ident           expands $Id$ in a shipped file.
#   filter          a smudge driver rewrites shipped bytes wholesale.
#   core.autocrlf   host config alone rewrites every text file, CRLF-ing the shell scripts.
#
# There is no switch that disables tree attributes, so the archive is verified against the
# object database instead. `git ls-tree` reports the mode and the blob hash of every path
# HEAD actually contains; a git blob hash is sha1("blob <len>\0" + bytes), which the checker
# recomputes from what landed in the stage. A missing path, an extra path, a changed byte, a
# committed symlink and a committed gitlink all fail here, together, for one reason: the
# stage must equal HEAD or nothing ships.
# shellcheck disable=SC2086  # deliberate, as above: newline-separated literal allowlists.
git ls-tree -r HEAD -- $FILES $DIRS > "$MANIFEST"
[ -s "$MANIFEST" ] || { echo "FAIL: HEAD contains none of the allowlisted paths"; exit 1; }
"$PY_FOR_SWEEP" - "$STAGE" "$MANIFEST" <<'VERIFY'
import hashlib
import pathlib
import sys

stage = pathlib.Path(sys.argv[1])
failures = []
expected = set()

for line in pathlib.Path(sys.argv[2]).read_text(encoding="utf-8").splitlines():
    meta, path = line.split("\t", 1)
    mode, kind, blob = meta.split()
    if path.startswith('"'):
        failures.append(f"{path}: the path needs quoting, so it carries a control character")
        continue
    if mode == "120000" or kind != "blob":
        failures.append(f"{path}: committed as mode {mode} ({kind}), which may not ship")
        continue
    expected.add(path)
    landed = stage / path
    if not landed.is_file():
        failures.append(f"{path}: in HEAD and not in the package (a .gitattributes export-ignore does this)")
        continue
    landed_mode = "100755" if landed.stat().st_mode & 0o111 else "100644"
    if landed_mode != mode:
        failures.append(f"{path}: mode {landed_mode} in the package against {mode} in HEAD")
    raw = landed.read_bytes()
    digest = hashlib.sha1(b"blob %d\0" % len(raw) + raw).hexdigest()  # noqa: S324
    if digest != blob:
        failures.append(f"{path}: {digest} in the package against {blob} in HEAD")

for landed in stage.rglob("*"):
    if landed.is_file() and str(landed.relative_to(stage)) not in expected:
        failures.append(f"{landed.relative_to(stage)}: in the package and not in HEAD")

for failure in failures:
    print(f"FAIL: {failure}")
if failures:
    sys.exit(1)
print(f"package verified against HEAD: {len(expected)} paths, every byte and mode matching")
VERIFY

# A symlink can still be COMMITTED, and `git archive` faithfully restores it as a link.
# Nothing in this package has any reason to be one, and `zip -r` without `-y` would store
# what it points at, so any link is refused rather than followed or preserved.
LINK="$(find "$STAGE" -type l -print -quit)"
[ -z "$LINK" ] || { echo "FAIL: $LINK is a symlink; the archiver would store what it points at"; exit 1; }

# By name. `.env.example` holds placeholders, is tracked, and the suite reads it from the
# package root, so it is the one name in this shape that must ship.
SECRET="$(find "$STAGE" ! -name '.env.example' \
               \( -name '.env' -o -name '.env.*' -o -name '*.pem' -o -name '*.key' \
                  -o -name 'id_rsa*' -o -name '*.p12' -o -name '*.pfx' \) -print -quit)"
[ -z "$SECRET" ] || { echo "FAIL: $SECRET looks like a credential and is in the package"; exit 1; }

# By CONTENT, because a name sweep is only a name sweep. A tracked file with an innocuous
# name and a credential inside it shipped in a clean-stamped package; the pre-write hook
# that would have caught it only runs on this assistant's own edits, so a human `git add`,
# a heredoc or a paste never passes through it. These are the hook's own patterns, so one
# rule set governs both routes into the repository. Be exact about "one rule set", because
# it is not identical: the hook's tenth rule (`Dockerfile ENV PORT`) is a build-contract
# check rather than a credential check and lives in the suite instead, and the hook matches
# one joined blob while this sweep matches line by line AND joined, so a split assignment is
# caught by both. A line carrying the project's existing `# noqa: S105` or `# nosec` marker
# is a declared test double and is skipped only inside the package's own top-level
# `tests/*.py`, anchored to the package root rather than matched anywhere in the path,
# because outside that the marker is a seven-character bypass for anyone who can commit.
"$PY_FOR_SWEEP" - "$STAGE" <<'SWEEP'
import pathlib
import re
import sys

RULES = [
    ("AWS access key id", r"\bAKIA[0-9A-Z]{16}\b"),
    ("Generic API key assignment",
     r"(?:api[_-]?key|secret|token|password|passwd|pwd)\s*[:=]\s*['\"][^'\"]{8,}['\"]"),
    ("Bearer token", r"\bBearer\s+[A-Za-z0-9._\-]{20,}\b"),
    ("Private key block", r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----"),
    ("LLM provider key", r"\b(?:sk-[A-Za-z0-9_\-]{20,}|sk-ant-[A-Za-z0-9_\-]{20,})\b"),
    ("Google API key", r"\bAIza[0-9A-Za-z_\-]{35}\b"),
    ("Slack token", r"\bxox[baprs]-[0-9A-Za-z\-]{10,}\b"),
    ("GitLab personal token", r"\bglpat-[0-9A-Za-z_\-]{20,}\b"),
    ("Client-side access gate", r"\b(?:ADMIN_)?PIN\s*=\s*['\"][0-9A-Za-z]{4,}['\"]"),
]
COMPILED = [(label, re.compile(pattern, re.IGNORECASE)) for label, pattern in RULES]

#: How many lines in the whole package may claim the exemption. It is honoured only for a
#: test module, because the exemption is a seven-character bypass for anyone who can commit:
#: appending `  # nosec` to a credential line made it ship. Exactly one line in this tree
#: needs it, the Entra test double, and pinning the count makes a second one a reviewed
#: change rather than a silent one.
EXEMPT_EXPECTED = 1
EXEMPT_MARKERS = ("# noqa: S105", "# nosec")


def _exempt(path, line):
    """Whether this line may claim the declared-test-double exemption.

    Anchored to the PACKAGE ROOT. `"tests" in path.parts` tested the absolute stage path,
    so any committed directory named `tests` anywhere satisfied it: `docs/tests/probe.py`
    with a marked credential shipped in a clean-stamped package, and the comment claiming
    the exemption applies only inside `tests/*.py` was false.
    """
    if not any(marker in line for marker in EXEMPT_MARKERS):
        return False
    parts = path.relative_to(STAGE).parts
    return len(parts) > 1 and parts[0] == "tests" and path.suffix == ".py"


STAGE = pathlib.Path(sys.argv[1])

hits = []
examined = 0
exempted = 0
found_on_a_line = set()
for path in pathlib.Path(sys.argv[1]).rglob("*"):
    if not path.is_file():
        continue
    try:
        raw = path.read_bytes()
    except OSError as error:
        # NOT a `continue`. A file the sweep cannot open is a file the sweep did not check,
        # and this is a credential control: the unexamined file is exactly where a secret
        # would be. The same principle the interpreter check above already states.
        hits.append(f"{path}: could not be read ({error.__class__.__name__})")
        continue
    # Decoded with replacement rather than skipped on a decode error. A single trailing
    # 0xFF byte appended to a Markdown file made `read_text` raise, the sweep moved on, and
    # the credential shipped in a package the build called clean. A credential inside a PNG
    # shipped the same way. Replacement never raises and still matches an ASCII pattern
    # embedded in binary, which is the shape that actually gets exfiltrated.
    # Two views of the same bytes. UTF-8 with replacement never raises, and it does not
    # SEE a UTF-16 file: the credential is there in plain sight as `s\x00k\x00-\x00`, and
    # no ASCII rule matches it. That is not an exotic encoding, it is what PowerShell's
    # `Out-File` and `>` produce by default, so a redirected capture pasted into the
    # repository lands in exactly this shape. Stripping the NUL bytes gives a second view
    # in which the same credential is ordinary ASCII, and it also covers UTF-32 and plain
    # NUL-interleaved text.
    #
    # What this still does NOT see, recorded because the accreditation record now names
    # this sweep as the compensating control for the whole secret regime: base64 or other
    # encodings of a credential, anything inside a compressed container, and a credential
    # carried in a filename rather than a file body. The last of those is closed just
    # below; the first two are open and are a real limit, not a theoretical one.
    text = raw.decode("utf-8", errors="replace")
    stripped = raw.replace(b"\x00", b"").decode("utf-8", errors="replace")
    examined += 1
    # Two passes over the same text. The line pass gives a number to report; the whole-file
    # pass catches an assignment split across lines, which the pre-write hook sees because
    # it matches one joined blob and a line-based sweep does not. Exempted lines are removed
    # before both, so the exemption cannot be defeated by the whole-file pass and cannot be
    # claimed by it either.
    scannable = []
    for number, line in enumerate(text.splitlines(), start=1):
        matched = [label for label, rule in COMPILED if rule.search(line)]
        marked = any(marker in line for marker in EXEMPT_MARKERS)
        if matched and marked:
            # Counted as claiming the exemption only when it would otherwise have been a
            # finding. A line that merely MENTIONS the marker, as this script's own tests
            # do when they write a probe, is not relying on it, and counting those made the
            # pinned total meaningless.
            if _exempt(path, line):
                exempted += 1
                continue
            hits.append(f"{path}:{number}: an exemption marker outside tests/*.py")
        scannable.append(line)
        for label in matched:
            hits.append(f"{path}:{number}: {label}")
            found_on_a_line.add((str(path), label))
    for label, rule in COMPILED:
        if rule.search("\n".join(scannable)) and (str(path), label) not in found_on_a_line:
            hits.append(f"{path}: {label}, split across lines")
    if stripped != text:
        for label, rule in COMPILED:
            if rule.search(stripped) and (str(path), label) not in found_on_a_line:
                hits.append(f"{path}: {label}, in a NUL-separated encoding such as UTF-16")
    # The NAME as well as the body. A key pasted as a filename never reaches the body scan.
    for label, rule in COMPILED:
        if rule.search(path.name):
            hits.append(f"{path.name}: {label}, in the filename")

if not examined:
    print("FAIL: the credential sweep examined no files at all")
    sys.exit(1)
if exempted != EXEMPT_EXPECTED:
    hits.append(f"{exempted} lines claimed the exemption against {EXEMPT_EXPECTED} expected")
for hit in hits:
    print(f"FAIL: {hit}")
if hits:
    sys.exit(1)
print(f"credential sweep: {examined} files examined, {EXEMPT_EXPECTED} declared exemption honoured")
SWEEP

# The assertion that would have caught the gate's finding. The suite reads these from the
# package root, so a package without them fails the platform test stage even though the
# same suite is green in the repository. Derived from the tests, not from memory:
# `grep -rn "parents\[1\]" tests/` names every one, and the list below is that grep's
# answer in full. The lockfiles are named here as well as in the allowlist above, because
# `_pins` reads all three from the package root and a second check costs nothing.
for needed in .env.example docs/DEPLOYMENT.md pyproject.toml Dockerfile \
              requirements-runtime.txt requirements.txt requirements-dev.txt; do
  [ -e "$STAGE/$needed" ] || { echo "FAIL: the suite reads $needed from the package root and it is not in the package"; exit 1; }
done
# A nested Dockerfile breaks template detection. There must be exactly one, at the root.
NESTED="$(find "$STAGE" -mindepth 2 -name Dockerfile -print | head -1)"
[ -z "$NESTED" ] || { echo "FAIL: nested Dockerfile at $NESTED breaks template detection"; exit 1; }
# No secret may ride along. `.env.example` holds placeholders only and is checked by the
# suite; a real `.env` is git-ignored and must never reach the package.
! [ -e "$STAGE/.env" ] || { echo "FAIL: .env is in the package"; exit 1; }
[ -f "$STAGE/.env.example" ] || { echo "FAIL: .env.example must ship; the suite reads it"; exit 1; }

(cd "$STAGE" && zip -q -r -X "../$(basename "$OUT")" . )
rm -rf "$STAGE"

# The builder names what it built. The simulation used to pick the newest zip by
# modification time, which meant parsing `ls` output and guessing; with two packages in
# `dist/` from different commits it is a guess that can be wrong, and it was.
# Written through a temporary name and moved into place, because `> dist/latest` writes
# through whatever path exists at that moment: a symlink planted in the build's own window
# redirected the pointer, and the artefact was written outside `dist/`. The SHA-256 goes
# beside it so the simulation can bind the pointer to the bytes rather than to a filename.
# Each temporary is removed IMMEDIATELY before it is written, not only at build start. A
# symlink planted at `dist/.latest.tmp` during the build was followed by the redirect and
# then moved onto `dist/latest` by `mv`, so the pointer itself became a link to a file
# outside `dist/`. Clearing the path at the moment of use closes the window the earlier
# fix left open.
rm -f "dist/.latest.tmp"
printf '%s\n' "$OUT" > "dist/.latest.tmp"
mv -f "dist/.latest.tmp" dist/latest
rm -f "dist/.latest.sha.tmp"
sha256sum "$OUT" | cut -d' ' -f1 > "dist/.latest.sha.tmp"
mv -f "dist/.latest.sha.tmp" dist/latest.sha256

echo "package: $OUT"
echo "size:    $(wc -c < "$OUT") bytes"
echo "sha256:  $(sha256sum "$OUT" | cut -d' ' -f1)"
echo "files:   $(unzip -Z1 "$OUT" | wc -l)"
