#!/bin/sh
# Build the App Store upload package: the artefact, and nothing that is not the artefact.
#
# This exists because the deploy gate found there was no artefact at all, so the thing
# that would be uploaded had never been built or tested. A plausible hand-assembled
# allowlist then went RED on the platform's own test stage in seconds, because the suite
# reads files from the package ROOT and two of them had not been shipped. A package is
# not a tarball of the repository and it is not the image build context either: the image
# excludes `tests/`, the platform requires them.
#
# Flat, with the Dockerfile at the root. A nested Dockerfile breaks both template
# detection and the build context, which is a recorded failure on this platform.
#
# Pure POSIX sh, like the verification loop, for the same reason.
set -eu

ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

# The content sweep below needs an interpreter. The project's own is preferred; a system
# python3 is accepted so the package can still be built on a machine without the virtual
# environment, and the absence of both is a hard failure rather than a silent skip, because
# this is a credential control.
PY_FOR_SWEEP=""
for candidate in "${PYTHON:-.venv/bin/python}" python3; do
  if command -v "$candidate" >/dev/null 2>&1; then PY_FOR_SWEEP="$candidate"; break; fi
done
[ -n "$PY_FOR_SWEEP" ] || { echo "FAIL: no interpreter for the credential sweep"; exit 1; }

VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -1)"
# A version with a slash in it makes $OUT and `basename "$OUT"` disagree, so the zip is
# written to one path while a different one is recorded, hashed and pointed at.
case "$VERSION" in
  "" | *[!0-9.]* ) echo "FAIL: implausible version '$VERSION' in pyproject.toml"; exit 1 ;;
esac
STAMP="$(date -u +%Y%m%d)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo nogit)"
# A package from a tree with uncommitted changes is stamped as such, so the simulation can
# refuse it. Without this, commit granularity admits a package built before an edit and the
# simulation reports PASS for a tree whose package was never built.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  COMMIT="${COMMIT}-dirty"
fi
OUT="dist/comply-ops-${VERSION}-${STAMP}-${COMMIT}.zip"
STAGE="dist/.stage"

# Every path that ships. Anything not named here is not in the package, so a new file
# that a test reads must be added HERE as well as written, and the assertion below is
# what catches the omission before the platform does.
FILES="Dockerfile
.dockerignore
.env.example
.python-version
pyproject.toml
sonar-project.properties
requirements-runtime.in
requirements-runtime.txt
requirements.in
requirements.txt
requirements-dev.in
requirements-dev.txt
wsgi.py
README.md
SECURITY.md
CHANGELOG.md"
DIRS="src
tests
docs
scripts"

# What is deliberately NOT shipped, and why, so the next person does not add it back:
#   .git, .github, .claude   history, CI and the assistant baseline are not the product
#   .venv, __pycache__       local build output
#   data/                    runtime state; the volume supplies it
#   dist/                    this script's own output
#   coverage.xml, sbom.*     regenerated by the platform's own run; a stale copy misleads
#   CLAUDE.md, READINESS.md  internal working documents
#   .gitlab-ci.yml           the platform generates its own pipeline; a shipped copy is
#                            inert at best and misleading at worst

# Invalidate the pointer BEFORE building, not after. It was only ever written on success
# and never cleared, so a build that failed left the previous commit's package still
# pointed at, and the simulation would test that stale artefact and report PASS for a tree
# whose package never built. Reproduced in a throwaway clone.
mkdir -p dist
rm -f dist/latest
rm -rf "$STAGE" "$OUT"
mkdir -p "$STAGE"

for path in $FILES; do
  [ -f "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
done
for path in $DIRS; do
  [ -d "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
done

# The stage is materialised from the OBJECT DATABASE, not from a walk of the working tree,
# and that is a security boundary rather than a tidiness preference. Two attacks made the
# case, both demonstrated rather than theorised.
#
# A directory copy ships whatever is on disk. A git-ignored `src/.env` is invisible to
# `git status`, so the tree reads clean, the package is stamped with a clean commit, and the
# secret is inside it. Reading the file list from `git ls-files` closed that, and left a
# second hole open: `cp` dereferences a symlink at any INTERMEDIATE path component, so
# replacing `docs/` with a link to a directory outside the tree put host-side content into
# the artefact while every leaf-level check passed. The sweep could not see it, because `cp`
# had already resolved it.
#
# `git archive HEAD` ends the class rather than narrowing it again. The bytes come from the
# committed tree, so an ignored file, an untracked file, a symlinked directory component, a
# hardlink swapped in on disk and an `assume-unchanged` bit are all equally invisible: none
# of them is in HEAD.
#
# The consequence is worth stating plainly. The package always contains HEAD, never the
# working tree. On a dirty tree it therefore packages the committed content and the `-dirty`
# stamp says so, which is the honest signal: the artefact does not represent what you are
# looking at.
# shellcheck disable=SC2086  # deliberate: both are newline-separated allowlists of
# literal paths this file controls, each checked to exist immediately above.
git archive HEAD -- $FILES $DIRS | tar -x -C "$STAGE"
[ -n "$(find "$STAGE" -type f -print -quit)" ] || { echo "FAIL: git archive produced nothing"; exit 1; }

# A symlink can still be COMMITTED, and `git archive` faithfully restores it as a link.
# Nothing in this package has any reason to be one, and `zip -r` without `-y` would store
# what it points at, so any link is refused rather than followed or preserved.
LINK="$(find "$STAGE" -type l -print -quit)"
[ -z "$LINK" ] || { echo "FAIL: $LINK is a symlink; the archiver would store what it points at"; exit 1; }

# By name. `.env.example` holds placeholders, is tracked, and the suite reads it from the
# package root, so it is the one name in this shape that must ship.
SECRET="$(find "$STAGE" ! -name '.env.example' \
               \( -name '.env' -o -name '.env.*' -o -name '*.pem' -o -name '*.key' \
                  -o -name 'id_rsa*' -o -name '*.p12' -o -name '*.pfx' \) -print -quit)"
[ -z "$SECRET" ] || { echo "FAIL: $SECRET looks like a credential and is in the package"; exit 1; }

# By CONTENT, because a name sweep is only a name sweep. A tracked file with an innocuous
# name and a credential inside it shipped in a clean-stamped package; the pre-write hook
# that would have caught it only runs on this assistant's own edits, so a human `git add`,
# a heredoc or a paste never passes through it. These are the hook's own patterns, so one
# rule set governs both routes into the repository. A line carrying the project's existing
# `# noqa: S105` or `# nosec` marker is a declared test double and is skipped, which is the
# convention the code already uses rather than a new one invented here.
"$PY_FOR_SWEEP" - "$STAGE" <<'SWEEP'
import pathlib
import re
import sys

RULES = [
    ("AWS access key id", r"\bAKIA[0-9A-Z]{16}\b"),
    ("Generic API key assignment",
     r"(?:api[_-]?key|secret|token|password|passwd|pwd)\s*[:=]\s*['\"][^'\"]{8,}['\"]"),
    ("Bearer token", r"\bBearer\s+[A-Za-z0-9._\-]{20,}\b"),
    ("Private key block", r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----"),
    ("LLM provider key", r"\b(?:sk-[A-Za-z0-9_\-]{20,}|sk-ant-[A-Za-z0-9_\-]{20,})\b"),
    ("Google API key", r"\bAIza[0-9A-Za-z_\-]{35}\b"),
    ("Slack token", r"\bxox[baprs]-[0-9A-Za-z\-]{10,}\b"),
    ("GitLab personal token", r"\bglpat-[0-9A-Za-z_\-]{20,}\b"),
    ("Client-side access gate", r"\b(?:ADMIN_)?PIN\s*=\s*['\"][0-9A-Za-z]{4,}['\"]"),
]
COMPILED = [(label, re.compile(pattern, re.IGNORECASE)) for label, pattern in RULES]

hits = []
for path in pathlib.Path(sys.argv[1]).rglob("*"):
    if not path.is_file():
        continue
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        continue
    for number, line in enumerate(text.splitlines(), start=1):
        if "# noqa: S105" in line or "# nosec" in line:
            continue
        for label, rule in COMPILED:
            if rule.search(line):
                hits.append(f"{path}:{number}: {label}")
for hit in hits:
    print(f"FAIL: {hit}")
sys.exit(1 if hits else 0)
SWEEP

# The assertion that would have caught the gate's finding. The suite reads these from the
# package root, so a package without them fails the platform test stage even though the
# same suite is green in the repository. Derived from the tests, not from memory:
# `grep -rn "parents\[1\]" tests/` names every one, and the list below is that grep's
# answer in full. The lockfiles are named here as well as in the allowlist above, because
# `_pins` reads all three from the package root and a second check costs nothing.
for needed in .env.example docs/DEPLOYMENT.md pyproject.toml Dockerfile \
              requirements-runtime.txt requirements.txt requirements-dev.txt; do
  [ -e "$STAGE/$needed" ] || { echo "FAIL: the suite reads $needed from the package root and it is not in the package"; exit 1; }
done
# A nested Dockerfile breaks template detection. There must be exactly one, at the root.
NESTED="$(find "$STAGE" -mindepth 2 -name Dockerfile -print | head -1)"
[ -z "$NESTED" ] || { echo "FAIL: nested Dockerfile at $NESTED breaks template detection"; exit 1; }
# No secret may ride along. `.env.example` holds placeholders only and is checked by the
# suite; a real `.env` is git-ignored and must never reach the package.
! [ -e "$STAGE/.env" ] || { echo "FAIL: .env is in the package"; exit 1; }
[ -f "$STAGE/.env.example" ] || { echo "FAIL: .env.example must ship; the suite reads it"; exit 1; }

(cd "$STAGE" && zip -q -r -X "../$(basename "$OUT")" . )
rm -rf "$STAGE"

# The builder names what it built. The simulation used to pick the newest zip by
# modification time, which meant parsing `ls` output and guessing; with two packages in
# `dist/` from different commits it is a guess that can be wrong, and it was.
printf '%s\n' "$OUT" > dist/latest

echo "package: $OUT"
echo "size:    $(wc -c < "$OUT") bytes"
echo "sha256:  $(sha256sum "$OUT" | cut -d' ' -f1)"
echo "files:   $(unzip -Z1 "$OUT" | wc -l)"
