#!/bin/sh
# Build the App Store upload package: the artefact, and nothing that is not the artefact.
#
# This exists because the deploy gate found there was no artefact at all, so the thing
# that would be uploaded had never been built or tested. A plausible hand-assembled
# allowlist then went RED on the platform's own test stage in seconds, because the suite
# reads files from the package ROOT and two of them had not been shipped. A package is
# not a tarball of the repository and it is not the image build context either: the image
# excludes `tests/`, the platform requires them.
#
# Flat, with the Dockerfile at the root. A nested Dockerfile breaks both template
# detection and the build context, which is a recorded failure on this platform.
#
# Pure POSIX sh, like the verification loop, for the same reason.
set -eu

ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' pyproject.toml | head -1)"
STAMP="$(date -u +%Y%m%d)"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo nogit)"
OUT="dist/comply-ops-${VERSION}-${STAMP}-${COMMIT}.zip"
STAGE="dist/.stage"

# Every path that ships. Anything not named here is not in the package, so a new file
# that a test reads must be added HERE as well as written, and the assertion below is
# what catches the omission before the platform does.
FILES="Dockerfile
.dockerignore
.env.example
.python-version
pyproject.toml
sonar-project.properties
requirements-runtime.in
requirements-runtime.txt
requirements.in
requirements.txt
requirements-dev.in
requirements-dev.txt
wsgi.py
README.md
SECURITY.md
CHANGELOG.md"
DIRS="src
tests
docs
scripts"

# What is deliberately NOT shipped, and why, so the next person does not add it back:
#   .git, .github, .claude   history, CI and the assistant baseline are not the product
#   .venv, __pycache__       local build output
#   data/                    runtime state; the volume supplies it
#   dist/                    this script's own output
#   coverage.xml, sbom.*     regenerated by the platform's own run; a stale copy misleads
#   CLAUDE.md, READINESS.md  internal working documents
#   .gitlab-ci.yml           the platform generates its own pipeline; a shipped copy is
#                            inert at best and misleading at worst

# Invalidate the pointer BEFORE building, not after. It was only ever written on success
# and never cleared, so a build that failed left the previous commit's package still
# pointed at, and the simulation would test that stale artefact and report PASS for a tree
# whose package never built. Reproduced in a throwaway clone.
mkdir -p dist
rm -f dist/latest
rm -rf "$STAGE" "$OUT"
mkdir -p "$STAGE"

for path in $FILES; do
  [ -f "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
  cp "$path" "$STAGE/$path"
done
for path in $DIRS; do
  [ -d "$path" ] || { echo "FAIL: $path is named in the allowlist and does not exist"; exit 1; }
  cp -R "$path" "$STAGE/$path"
done

# Local build output can ride along inside a copied directory. Remove it rather than
# trusting that it was never generated: an uploaded __pycache__ is a stale-bytecode
# failure waiting for a Python version difference to surface it.
find "$STAGE" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
find "$STAGE" -name '*.pyc' -delete 2>/dev/null || true
find "$STAGE" -name '.DS_Store' -delete 2>/dev/null || true

# The assertion that would have caught the gate's finding. The suite reads these from the
# package root, so a package without them fails the platform test stage even though the
# same suite is green in the repository. Derived from the tests, not from memory:
# `grep -rn "parents\[1\]" tests/` names every one, and the list below is that grep's
# answer in full. The lockfiles are named here as well as in the allowlist above, because
# `_pins` reads all three from the package root and a second check costs nothing.
for needed in .env.example docs/DEPLOYMENT.md pyproject.toml Dockerfile \
              requirements-runtime.txt requirements.txt requirements-dev.txt; do
  [ -e "$STAGE/$needed" ] || { echo "FAIL: the suite reads $needed from the package root and it is not in the package"; exit 1; }
done
# A nested Dockerfile breaks template detection. There must be exactly one, at the root.
NESTED="$(find "$STAGE" -mindepth 2 -name Dockerfile -print | head -1)"
[ -z "$NESTED" ] || { echo "FAIL: nested Dockerfile at $NESTED breaks template detection"; exit 1; }
# No secret may ride along. `.env.example` holds placeholders only and is checked by the
# suite; a real `.env` is git-ignored and must never reach the package.
! [ -e "$STAGE/.env" ] || { echo "FAIL: .env is in the package"; exit 1; }

(cd "$STAGE" && zip -q -r -X "../$(basename "$OUT")" . )
rm -rf "$STAGE"

# The builder names what it built. The simulation used to pick the newest zip by
# modification time, which meant parsing `ls` output and guessing; with two packages in
# `dist/` from different commits it is a guess that can be wrong, and it was.
printf '%s\n' "$OUT" > dist/latest

echo "package: $OUT"
echo "size:    $(wc -c < "$OUT") bytes"
echo "sha256:  $(sha256sum "$OUT" | cut -d' ' -f1)"
echo "files:   $(unzip -Z1 "$OUT" | wc -l)"
